// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface PageStoryblok {
  body?: PageStoryblok[];
  component: "page";
  _uid: string;
  [k: string]: any;
}
